### ISSUE TITLE
Doesn't seem to work with the current Master

### ISSUE THREAD

**Issue by gitxmax** [kbahey/onstep-python#2]
Tried using the script, so far, only the homing menu seems to work.
When i try to run the backlash compensation, after centering the object and, as per the guidance to end with the "East" key, nothing happens, even though the message says, "moving away from the object".

A few more errors I get..

Running stress test, I get the following error:

`  File "./examples/menu.py", line 51, in <module>
    func()
  File "/home/astroberry/onstep-python/examples/drift_test.py", line 41, in drift_test
    ra = float(equ_decimal.split(',')[0])
ValueError: could not convert string to float:
`
Running Drift Test:

`  File "./examples/menu.py", line 51, in <module>
    func()
  File "/home/astroberry/onstep-python/examples/drift_test.py", line 41, in drift_test
    ra = float(equ_decimal.split(',')[0])
ValueError: could not convert string to float:
`

Have a german type EQ mount, if that matters, I also tried swithching to alt/az, but no difference.
Thanks.

**Comment by kbahey** [comment]
Both the drift test and backlash proceed without any errors.
I am using Python3
Here is what I get when I do the drift test:
``
Time            OnStep Time   Sidereal      St  RA            DE        Equ                  RAdlta RA"/min RA"Max DE"/min DE"Max
14:54:48.054491 14:54:48.3587 22:33:34.7700 N/A 05:32:02.8294 +89*55:49 68.311142,89.932569   0.00   0.00   0.00   0.00   0.00
14:54:58.415899 14:54:58.7702 22:33:45.2100 N/A 05:32:13.2694 +89*55:49 68.354642,89.932569   0.00 938.85 156.47   0.00   0.00
14:55:08.779119 14:55:09.1817 22:33:55.6500 N/A 05:32:23.7094 +89*55:49 68.398142,89.932569 156.47 938.85 312.95   0.00   0.00
14:55:19.141584 14:55:19.5932 22:34:06.1000 N/A 05:32:34.1494 +89*55:49 68.441642,89.932569 156.47 908.56 469.42   0.00   0.00
14:55:29.505572 14:55:30.0146 22:34:16.5400 N/A 05:32:44.5894 +89*55:49 68.485184,89.932569 156.63 916.17 626.05   0.00   0.00
14:55:39.867888 14:55:40.4261 22:34:26.9800 N/A 05:32:55.0294 +89*55:49 68.528684,89.932569 156.47 920.62 782.53   0.00   0.00
``

**Comment by gitxmax** [comment]
from the experience, different versions of python3 act differently. Would be helpful to know, which version you used.

**Comment by kbahey** [comment]
Should not be the case here. Nothing esoteric in my code.

I am using 3.6.9 (the one in Ubuntu 18.04 repos).

**Comment by gitxmax** [comment]
Need to check mine, most likely 3.8, as it's a fresh installation of the Raspbian. Any idea, what could possibly cause those errors, if not the python3 different version?

**Comment by kbahey** [comment]
No idea specifically.

But as per the read me, you need to enter your coordinates in examples/config.py.
At a minimum uncomment lat and lon and put some valid values there. 

Then set ra and de to some star that is above the horizon.

Then run ./examples/menu.py

From there, select Initialize, then Slew to a Star.
While the mount is slewing, select Report Status and see if it changes to TRK and the coordinates of the star.
